### ISSUE TITLE
Apostrophe is not Rendered in WI Title [DUP #807]

### ISSUE THREAD

**Issue by mindreeper2420** [fabric8-ui/fabric8-planner#1241]
When entering a Work Item title with an apostrophe, the apostrophe is not rendered correctly.

<img width="1445" alt="screen shot 2017-03-21 at 10 11 02 am" src="https://cloud.githubusercontent.com/assets/4032718/24151291/bb829c7e-0e1e-11e7-930d-6717ab580e5e.png">

**Comment by debloper** [comment]
Related to #807 and almighty/almighty-core#708

**Comment by mindreeper2420** [comment]
outdated - closing
