### ISSUE TITLE
Bug: Logged Out, But Assign To Me Still Filters

### ISSUE THREAD

**Issue by mindreeper2420** [fabric8-ui/fabric8-planner#1456]
I'm a logged out user, but I can still filter by 'Assigned to Me' and see items that are assigned to my account. The filter option 'Assigned to Me' should not be available if a user is logged out.

Steps to Replicate (iteration 1):
- Log in to prod-preview
- Go to a backlog (I used adamjolicoeur/myworld/plan)
- Log Out
- From Filter dropdown, select 'Assigned to Me'
- Backlog List is filtered by my name
<img width="1440" alt="screen shot 2017-04-04 at 2 26 15 pm" src="https://cloud.githubusercontent.com/assets/4032718/24672611/5e5ff980-1943-11e7-8c0f-5aa379cb2548.png">

Steps to Replicate (iteration 2):
- Go to http://prod-preview.openshift.io/adamjolicoeur/myworld/plan
- From the Filter dropdown, select 'Assigned to Me'
- The filter bar tells me that the list has been filtered by 'Assigned to Me', but nothing is actually filtered
<img width="1440" alt="screen shot 2017-04-04 at 2 31 53 pm" src="https://cloud.githubusercontent.com/assets/4032718/24672767/e6eebb38-1943-11e7-8e2f-0f78e2a44782.png">

**Comment by nimishamukherjee** [comment]
@muruGanesan @mindreeper2420 can you confirm if the below behaviour  fine:
Referring to - https://redhat.invisionapp.com/share/56AH8F1XM#/screens/219275641
**When a user is logged out:**
1. "Assign to me" filter option should not show up
2. Area filter should work
3. Type filter should work
4. Status filter should work
5. Type filter (in board view) should work

**Comment by mindreeper2420** [comment]
@nimishamukherjee that is correct. A user should not be able to filter by the 'Assign to Me' option if they are logged out. If possible, the ability to filter by any user should still be an option, even to a logged out user.

**Comment by mindreeper2420** [comment]
outdated - closing
