### ISSUE TITLE
Relationship link to show work item parent

### ISSUE THREAD

**Issue by baijum** [fabric8-ui/fabric8-planner#1738]
```
"parent": {
   "links": {
      "related": "https://example.org/api/spaces/{Space-ID}/workitems/{WI-ID}"
},
```

**Comment by baijum** [comment]
The links API has this info already. `https://example.org/api/spaces/{Space-ID}/workitems/{WI-ID}/relationships/links` So, do we need this API?

**Comment by baijum** [comment]
@michaelkleinhenz Can you please let me know the use case?

**Comment by michaelkleinhenz** [comment]
The usecase is that we can now see if a WI has a parent. This helps when rendering the tree view as part of the list view. But this has low priority right now. So if there is other things with higher prio, do these first :-)
