### ISSUE TITLE
Update Save Model for Input Fields

### ISSUE THREAD

**Issue by mindreeper2420** [fabric8-ui/fabric8-planner#182]
The Save Model should follow the designs as listed in the [Save Existing & New Changes](https://redhat.invisionapp.com/share/4N8Y3BSAD#/193330599_Panel_Edit_-_Title) prototype.

Each input field should have a Cancel and Save option. This replaces the overall Cancel/Save that currently exists.

Keyboard controls will do the following:
- Esc = Cancel Input/Changes
- Enter/Return = Accept/Save Input/Changes
- Tab = Tab between elements
  - Start in Input
  - Tab to Cancel (X)
    - Enter to commit
  - Tab to Save (checkmark)
    - Enter to commit
- Tabbing to the next input will save your changes (just like clicking the checkmark)

**Comment by joshuawilson** [comment]
@nimishamukherjee can you please work with @mindreeper2420 to verify what still needs to be done for this.

**Comment by nimishamukherjee** [comment]
@joshuawilson tabbing needs to be implemented.

**Comment by sanbornsen** [comment]
Comment
