### ISSUE TITLE
Work Item IDs should be incremented based on the context (user/org or space)

### ISSUE THREAD

**Issue by baijum** [fabric8-ui/fabric8-planner#1843]
Currently, the work item IDs are universal across the system. The ID is incremented to the next value irrespective which user/org or space that work item belongs.

I would suggest making the value based on the context.  We can either use user/org as the context or space as the context.

I think user/org as the context is better for communication between teams. Otherwise, space should be specified every time they mention about a work item (think about a conversation happening over the phone).

**Comment by maxandersen** [comment]
if the number is across user/org's it would require renumbering everything when moving a space to another user/org. Since a workitem cannot exist *outside* a space I would say space is the proper scope.

**Comment by baijum** [comment]
@maxandersen Moving spaces across user/org would be an interesting feature. So, I am fine with using space as the context for IDs.
