### ISSUE TITLE
New Work Item Labels Are Just "Labels"

### ISSUE THREAD

**Issue by mindreeper2420** [fabric8-ui/fabric8-planner#1924]
When I create a New Work Item using the Detail Panel, all of the Labels just have the text "Labels".

<img width="878" alt="screen shot 2017-05-24 at 9 51 26 pm" src="https://cloud.githubusercontent.com/assets/4032718/26432665/569d4e0a-40cb-11e7-8a0d-d34be7197a32.png">

**Comment by debloper** [comment]
Can't reproduce, please verify @mindreeper2420

**Comment by mindreeper2420** [comment]
outdated - closing
