### ISSUE TITLE
workitem UI: Edit WI (Task), recreates the task

### ISSUE THREAD

**Issue by joshuawilson** [fabric8-ui/fabric8-planner#1973]
_From @burrsutter on June 6, 2017 14:59_

https://screencast.com/t/b11xv8PGF

Editing the Description causes a new WI to be created

_Copied from original issue: openshiftio/openshift.io#196_

**Comment by joshuawilson** [comment]
I have found that I can just click the "check mark" multiple times to create copies during the creation of a WI.

**Comment by burrsutter** [comment]
Edited the description and seems to duplicate the WI
https://screencast.com/t/Urw8Ai7e7lf
