### ISSUE TITLE
Configure functional tests to run on Fabric8 - http://jenkins.cd.k8s.fabric8.io/blue/organizations/jenkins/pipelines

### ISSUE THREAD

**Issue by ldimaggi** [fabric8-ui/fabric8-planner#2016]
The functional tests are currently running - and failing - it looks like a chrome issue as the tests cannot "find" any of the UI elements:

https://github.com/fabric8io/fabric8-planner/pull/2003

http://jenkins.cd.k8s.fabric8.io/blue/organizations/jenkins/pipelines

http://jenkins.cd.k8s.fabric8.io/blue/organizations/jenkins/auto%2Ffabric8-planner/pr

http://jenkins.cd.k8s.fabric8.io/blue/organizations/jenkins/auto%2Ffabric8-planner/detail/PR-2003/11/pipeline

**Comment by ldimaggi** [comment]
Once the tests are running reliably - we should move them to the new test repo:

https://github.com/fabric8io/fabric8-test/tree/master/ui_tests

**Comment by hectorj2f** [comment]
Closing this issue! They are running now
