### ISSUE TITLE
Add 'Blocked' status to a task

### ISSUE THREAD

**Issue by joshuawilson** [fabric8-ui/fabric8-planner#2031]
_From @rgarg1 on June 21, 2017 7:15_

This will clearly display the task status for the team on the Kanban board, which otherwise right could see it as 'In-progress' and the blocked status could be retrieved only after opening the task. 

This is much needed to draw attention of the team to its blocked state.

_Copied from original issue: openshiftio/openshift.io#270_

**Comment by qodfathr** [comment]
Per commentary on https://github.com/openshiftio/openshift.io/issues/270, I recommend closing this issue.
