### ISSUE TITLE
Adapt to new API for work items

### ISSUE THREAD

**Issue by xcoulon** [fabric8-ui/fabric8-planner#2049]
See https://github.com/fabric8-services/fabric8-wit/pull/1457 which changes the API for showing and updating a given work item: the URL template will become `/api/workitems/<work_item_id>`, ie, the `/spaces/<space_id>` part disappears in this case (but remains for the `create`, `list` and `reorder` operations).

**Comment by hectorj2f** [comment]
@michaelkleinhenz is there any progress in here ?

**Comment by hectorj2f** [comment]
Closing this issues! it was addressed by #2077
