### ISSUE TITLE
"View all Spaces" returns random subsets of a user's spaces

### ISSUE THREAD

**Issue by ldimaggi** [fabric8-ui/fabric8-planner#2055]
I first started seeing this issue on July 3 - when a user views all spaces, random subsets of that user's spaces are seen:

![screenshot from 2017-07-03 14-26-01](https://user-images.githubusercontent.com/642621/27805194-403d941c-6001-11e7-9e9e-1cb7bfcf3fe8.png)

![screenshot from 2017-07-03 14-45-19](https://user-images.githubusercontent.com/642621/27805201-494de228-6001-11e7-83d5-3281b38e6837.png)

**Comment by aslakknutsen** [comment]
This is a f8-ui issue, not planner. But possible caused by no pagination support in the UI and random returned order from server.

**Comment by joshuawilson** [comment]
This issue was moved to fabric8-ui/fabric8-ui#1626

**Comment by ldimaggi** [comment]
Deleting spaces does not affect this bug - random subsets of the remaining spaces are seen.
