### ISSUE TITLE
No clickable mouse icon on clickable items

### ISSUE THREAD

**Issue by jarifibrahim** [fabric8-ui/fabric8-planner#2201]
All the items (including the cross icon) are clickable but the cursor does not change on hovering over the items
![plan backlog openshift io tooltip](https://user-images.githubusercontent.com/12949454/31118797-48b0bde8-a84c-11e7-993a-920cdacdc53a.png)

**Comment by rgarg1** [comment]
Tracking via https://openshift.io/openshiftio/openshiftio/plan/detail/1553
