### ISSUE TITLE
'show more' button should not be visible

### ISSUE THREAD

**Issue by jarifibrahim** [fabric8-ui/fabric8-planner#2202]
By default the `show more` button is visible. It should be hidden.

![screenshot from 2017 10 03 16 02 58](https://user-images.githubusercontent.com/12949454/31121270-27728cd4-a855-11e7-8aab-6c85b1696cfa.png)

**Comment by rgarg1** [comment]
Tracking via https://openshift.io/openshiftio/openshiftio/plan/detail/1552
