### ISSUE TITLE
Incorrect placement of down icon

### ISSUE THREAD

**Issue by jarifibrahim** [fabric8-ui/fabric8-planner#2205]
The down icon should be on the button (next to work item type icon) and not in the modal.

![plan backlog openshift io](https://user-images.githubusercontent.com/12949454/31162759-cd16fe2a-a8fc-11e7-86a9-4373e45b0a00.png)

**Comment by rgarg1** [comment]
https://openshift.io/openshiftio/openshiftio/plan/detail/1551
