### ISSUE TITLE
Create new workitem page takes too long to appear

### ISSUE THREAD

**Issue by jarifibrahim** [fabric8-ui/fabric8-planner#2209]
Steps to reproduce -

1. Click on `create` work item button
2. Select any work item type
3. Wait for 3 secs

1.. 2.. 3.. Tada!! The new work creation page appears after 3 sec.

![screencast from 10-03-2017 03-19-42 pm](https://user-images.githubusercontent.com/12949454/31169250-a2ea7154-a915-11e7-9f6c-9125c60a39e5.gif)

**Comment by rgarg1** [comment]
Tracking via https://openshift.io/openshiftio/openshiftio/plan/detail/1548
