### ISSUE TITLE
Work-Item-quick-add form alignment breaks for certain work items

### ISSUE THREAD

**Issue by jarifibrahim** [fabric8-ui/fabric8-planner#2210]
![screencast from 10-04-2017 03-12-30 pm](https://user-images.githubusercontent.com/12949454/31169703-20d991d4-a917-11e7-8040-5a9f8b84b849.gif)

**Comment by rgarg1** [comment]
Tracking via https://openshift.io/openshiftio/openshiftio/plan/detail/1547
