### ISSUE TITLE
Updating child iteration end date does not update UI

### ISSUE THREAD

**Issue by jarifibrahim** [fabric8-ui/fabric8-planner#2213]
PS - The date is updated if you refresh the page

![screencast from 10-04-2017 04-49-29 pm](https://user-images.githubusercontent.com/12949454/31173249-6b2b4554-a924-11e7-9a34-f58f8f50c9ce.gif)

**Comment by jarifibrahim** [comment]
The same issue exists with start date as well.

**Comment by rgarg1** [comment]
Tracking via https://openshift.io/openshiftio/openshiftio/plan/detail/1545
