### ISSUE TITLE
Clicking on Iteration div does not work

### ISSUE THREAD

**Issue by jarifibrahim** [fabric8-ui/fabric8-planner#2215]
Clicking on iteration div 
Works when - User clicks on upper half of the iteration div
Does not work when - User clicks on the lower half of the iteration div
![screencast from 10-05-2017 05-27-35 pm](https://user-images.githubusercontent.com/12949454/31226229-fd558eac-a9f2-11e7-99dc-3908d1f5cc5a.gif)

**Comment by rgarg1** [comment]
Tracking via https://openshift.io/openshiftio/openshiftio/plan/detail/1544
