### ISSUE TITLE
Quick add "bug" not easily clickable

### ISSUE THREAD

**Issue by jarifibrahim** [fabric8-ui/fabric8-planner#2254]
If you click on lower half of the bug div, it takes two clicks. If you click on upper part, it takes one.

![screencast from 10-10-2017 11-46-30 am](https://user-images.githubusercontent.com/12949454/31371891-f8a7610c-adb0-11e7-9a8e-e42121743e34.gif)

**Comment by rgarg1** [comment]
Tracking via https://openshift.io/openshiftio/openshiftio/plan/detail/1543
