### ISSUE TITLE
Work item does not disappear after changing it's iteration

### ISSUE THREAD

**Issue by jarifibrahim** [fabric8-ui/fabric8-planner#2255]
Steps to reproduce;
1. Associate a work item, say "Iteration 2"
2. Go to Iteration 2, click on the same work item and associate it with different iteration.

Expected Behavior - Work item should disappear from iteration 2

![screencast from 10-10-2017 12-04-20 pm](https://user-images.githubusercontent.com/12949454/31372480-82f87b64-adb3-11e7-9c39-f54eab93426c.gif)

**Comment by rgarg1** [comment]
tracking via https://openshift.io/openshiftio/openshiftio/plan/detail/1542
