### ISSUE TITLE
Label search should not be case sensitive

### ISSUE THREAD

**Issue by jarifibrahim** [fabric8-ui/fabric8-planner#2258]
![labelcasesensitive](https://user-images.githubusercontent.com/12949454/31380808-17a08178-add0-11e7-830e-cf152f25f68c.gif)

**Comment by rgarg1** [comment]
Similar to https://github.com/fabric8-ui/fabric8-planner/issues/2190

**Comment by jarifibrahim** [comment]
Closing this in favor of https://github.com/fabric8-ui/fabric8-planner/issues/2190
