### ISSUE TITLE
Child iterations are not indented

### ISSUE THREAD

**Issue by jarifibrahim** [fabric8-ui/fabric8-planner#2259]
In the attached gif, iterations do not appear indented.

The iterations should be according to the following hierarchy

- Iteration 1
-- Child 1
--- Child 2
---- Child 4
-- Iteration 2
- Iteration 3

![iterationindentation](https://user-images.githubusercontent.com/12949454/31384877-83a13c24-adde-11e7-93ff-65ca67ca8700.gif)

**Comment by rgarg1** [comment]
Created https://openshift.io/openshiftio/openshiftio/plan/detail/1535 for tracking this in OSIO
