### ISSUE TITLE
Unexpected scroll bar on planner UI when user is not logged in

### ISSUE THREAD

**Issue by DhritiShikhar** [fabric8-ui/fabric8-planner#2301]
When a user is not logged in, the planner shows a scrollable side bar which is not expected 

![xzqogpotklmlspca](https://user-images.githubusercontent.com/6303309/31942238-37b4b45e-b8b4-11e7-9788-0b32e52c1dcd.png)

**Comment by SMahil** [comment]
@DhritiShikhar Please verify this issue

**Comment by DhritiShikhar** [comment]
@SMahil cannot reproduce this anymore
