### ISSUE TITLE
Unintended display of workitem children

### ISSUE THREAD

**Issue by DhritiShikhar** [fabric8-ui/fabric8-planner#2340]
Scenario:
This particular workitem (workitem number 16) is both on top-level as well as nested. 

When I select the nested item:
- its children are displayed
- the top-level item's children are also displayed.

This is not ideal. When a nested item is clicked, it should not trigger the top level item to also display its children and vice-versa.

https://youtu.be/l910cF2tQCU

**Comment by rgarg1** [comment]
@DhritiShikhar Kindly log all planner defects in Planner itself. Thanks

**Comment by DhritiShikhar** [comment]
@rgarg1 Thanks for reminding. I will create a workitem in Planner.

**Comment by DhritiShikhar** [comment]
Planner workitem: https://openshift.io/openshiftio/openshiftio/plan/detail/1729

**Comment by DhritiShikhar** [comment]
This is resolved
