### ISSUE TITLE
Quotes do not get rendered properly in description and comments

### ISSUE THREAD

**Issue by dharmit** [fabric8-ui/fabric8-planner#2351]
Single/double quotes do not get rendered properly when writing in code-blocks.

![screenshot from 2017-11-23 15-20-48](https://user-images.githubusercontent.com/713521/33468945-d8154ffa-d685-11e7-8975-0aced1b7bb17.png)

**Comment by jarifibrahim** [comment]
This is being tracked in https://github.com/openshiftio/openshift.io/issues/3875.
