### ISSUE TITLE
Remove old JS based functional tests

### ISSUE THREAD

**Issue by jarifibrahim** [fabric8-ui/fabric8-planner#2599]
We now have TS based functional tests in `src/tests` directory and we should remove the old tests in the `runtime/src/tests` directory.

Tasks

- [x] Move `google-chrome.repo` file out of `runtime/tests` directory
- [x] Delete `runtime/tests` directory
- [x] Delete `runtime/src/tests` directory 

@rgarg1 @Raunak1203 What do you think?

**Comment by rgarg1** [comment]
I'm okay with this if we have done an audit of the old tests to ensure that we've automated (or ported, or borrowed) all older tests. I mean we should use the older tests just as a ref to write brand new tests.
There could be great old tests that just don't run anymore, but we may want to bring them to life.

**Comment by jarifibrahim** [comment]
@rgarg1 I'll do an audit of the JS based tests and ensure we do not lose any tests

**Comment by Raunak1203** [comment]
As discussed with @rgarg1, we have covered almost all the tests in typescript and are also adding new tests in typescript. So, It makes sense now to remove the old JS code.

**Comment by Raunak1203** [comment]
fixed with PR https://github.com/fabric8-ui/fabric8-planner/pull/2732
