### ISSUE TITLE
Improve test coverage of AlmSearchHighlight pipe

### ISSUE THREAD

**Issue by ppitonak** [fabric8-ui/fabric8-planner#346]
New unit tests for AlmSearchHighlight should be created:

- should work when first parameter is an empty string
- should work when second parameter is an empty string
- should work when highlighting special characters such as !@#$%^&*()_+{}[]"|,./<>?`~

I'm not sure what should happen when search pattern contains only white spaces. Now it does following which doesn't feel right:

```
transform('Some string', ' ') => 'Some<b> </b>string'
```

**Comment by joshuawilson** [comment]
@sanbornsen I think this is for you. Maybe @naina-verma and @ldimaggi could help.

**Comment by sanbornsen** [comment]
Thanks @ppitonak. I'll work on that. And the output of the case you have mentioned, should be alright.
