### ISSUE TITLE
Create unit tests for authentication service

### ISSUE THREAD

**Issue by ppitonak** [fabric8-ui/fabric8-planner#347]
There is not a single test for authentication service

**Comment by joshuawilson** [comment]
@ppitonak I think @naina-verma just wrote some Functional tests on this. Do they satisfy this issue?

**Comment by ppitonak** [comment]
@joshuawilson No, I believe that we should have some basic unit tests for AuthenticationService - this class contains 3 non-trivial methods with no docs and a lot of lines with commented code (mainly navigation).

**Comment by joshuawilson** [comment]
@nimishamukherjee @sanbornsen can you please look into this.
