### ISSUE TITLE
Logout doesn't work properly

### ISSUE THREAD

**Issue by ppitonak** [fabric8-ui/fabric8-planner#356]
Auth token is not invalidated when user logs out using UI

1. open demo.almighty.io, login and open console
2. in console: `let auth_token = localStorage.getItem('auth_token')`
3. log out using link in top-right corner
4. in console: `localStorage.setItem('auth_token', auth_token)`
5. refresh the page
6. create new item using quick add component

**Comment by sanbornsen** [comment]
@ppitonak yes, we don't have expiration in backend right now. Your steps would clearly make the user logged in again. In order to fix this we need to have an endpoint where we can expire the token from backend itself on login.
@aslakknutsen what do you think?

**Comment by nimishamukherjee** [comment]
Points to be noted:
1. The token needs to be stored locally until the user logs out. This is one of the UX requirements where the user remains logged in even if they close the browser.

2. The token is a Github token. The same token is generated based on who logs in. In this scenario, currently the core cannot invalidate the token.

@ppitonak @joshuawilson @aslakknutsen could you let us know on how do we proceed with this?

**Comment by joshuawilson** [comment]
@kbsingh do you have any insight into this?
