### ISSUE TITLE
[BUG] Selecting Work Item does not always change detail panel

### ISSUE THREAD

**Issue by mindreeper2420** [fabric8-ui/fabric8-planner#876]
I selected one Work Item from the list view and then attempted to select another from another point in the list (without first closing the initial detail panel). I was unable to see the selected item in the detail panel, but the row highlighted as if it was active.

<img width="1442" alt="screen shot 2017-02-02 at 1 43 12 pm" src="https://cloud.githubusercontent.com/assets/4032718/22549955/1e621bda-e94e-11e6-9ed6-18acdafd60fe.png">

**Comment by Ritsyy** [comment]
@mindreeper2420 I am not able to reproduce this bug now, can you try it now again?
