### ISSUE TITLE
Update Error Handling for Input Fields

### ISSUE THREAD

**Issue by mindreeper2420** [fabric8-ui/fabric8-planner#952]
Currently, the error handling does not follow the patterns set forth in PatternFly. As such, they need to be adjusted to properly fit the schematics that are in use.

Please refer to this wireframe: https://redhat.invisionapp.com/share/UAACVQ7XT
Reference is also available on the patternfly.org blog: https://blog.patternfly.org/required-fields/

**Comment by Essjaysee** [comment]
Do we have a list of the possible errors?  I'd like to review the message copy.  Thanks!

**Comment by Mgranfie** [comment]
Not that I know of. Let me ask Joshua and see if they are keeping a
resource file in the code... as promised early on LOL
